---
# tasks file for infra_client_dhcp_relayagent

# install dhcp relay agent
- name: install dhcp relay agent
  ansible.builtin.dnf:
    name: "{{ dhcp_relayagent_package }}"
    state: present

# configure dhcrelay.service
- name: configure dhcprelay.service
  ansible.builtin.template:
    src: dhcrelay.service.j2
    dest: /etc/systemd/system/dhcrelay.service

# Reload the systemd manager configuration: 
- name: reload the systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes

# enable and start dhcrelay.service
- name: enable and start dhcrelay.service
  ansible.builtin.service:
    name: dhcrelay.service
    state: started
    enabled: yes
